src/Entity/Restaurant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RestaurantRepository")
 */
class Restaurant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover_photo;

    /**
     * @ORM\Column(type="integer")
     */
    private $amount_of_tables;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $layout_photo;

    /**
     * @ORM\Column(type="integer")
     */
    private $registration_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $working_status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slogan;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="restaurant")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RestaurantTable", mappedBy="restaurant", orphanRemoval=true)
     */
    private $restaurantTables;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="restauran", orphanRemoval=true)
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="restaurant", orphanRemoval=true)
     */
    private $reviews;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Bookmark", mappedBy="restaurant", orphanRemoval=true)
     */
    private $bookmarks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="restaurant", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->restaurantTables = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->bookmarks = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getOwner(): ?string
    {
        return $this->owner;
    }

    public function setOwner(?string $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCoverPhoto(): ?string
    {
        return $this->cover_photo;
    }

    public function setCoverPhoto(string $cover_photo): self
    {
        $this->cover_photo = $cover_photo;

        return $this;
    }

    public function getAmountOfTables(): ?int
    {
        return $this->amount_of_tables;
    }

    public function setAmountOfTables(int $amount_of_tables): self
    {
        $this->amount_of_tables = $amount_of_tables;

        return $this;
    }

    public function getLayoutPhoto(): ?string
    {
        return $this->layout_photo;
    }

    public function setLayoutPhoto(string $layout_photo): self
    {
        $this->layout_photo = $layout_photo;

        return $this;
    }

    public function getRegistrationDate(): ?int
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(int $registration_date): self
    {
        $this->registration_date = $registration_date;

        return $this;
    }

    public function getWorkingStatus(): ?bool
    {
        return $this->working_status;
    }

    public function setWorkingStatus(bool $working_status): self
    {
        $this->working_status = $working_status;

        return $this;
    }

    public function getSlogan(): ?string
    {
        return $this->slogan;
    }

    public function setSlogan(?string $slogan): self
    {
        $this->slogan = $slogan;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|RestaurantTable[]
     */
    public function getRestaurantTables(): Collection
    {
        return $this->restaurantTables;
    }

    public function addRestaurantTable(RestaurantTable $restaurantTable): self
    {
        if (!$this->restaurantTables->contains($restaurantTable)) {
            $this->restaurantTables[] = $restaurantTable;
            $restaurantTable->setRestaurant($this);
        }

        return $this;
    }

    public function removeRestaurantTable(RestaurantTable $restaurantTable): self
    {
        if ($this->restaurantTables->contains($restaurantTable)) {
            $this->restaurantTables->removeElement($restaurantTable);
            // set the owning side to null (unless already changed)
            if ($restaurantTable->getRestaurant() === $this) {
                $restaurantTable->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setRestauranId($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getRestauranId() === $this) {
                $reservation->setRestauranId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setRestaurant($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getRestaurant() === $this) {
                $review->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Bookmark[]
     */
    public function getBookmarks(): Collection
    {
        return $this->bookmarks;
    }

    public function addBookmark(Bookmark $bookmark): self
    {
        if (!$this->bookmarks->contains($bookmark)) {
            $this->bookmarks[] = $bookmark;
            $bookmark->setRestaurant($this);
        }

        return $this;
    }

    public function removeBookmark(Bookmark $bookmark): self
    {
        if ($this->bookmarks->contains($bookmark)) {
            $this->bookmarks->removeElement($bookmark);
            // set the owning side to null (unless already changed)
            if ($bookmark->getRestaurant() === $this) {
                $bookmark->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setRestaurant($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getRestaurant() === $this) {
                $comment->setRestaurant(null);
            }
        }

        return $this;
    }
}

src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Restaurant", inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $restaurant;

    /**
     * @ORM\Column(type="time")
     */
    private $review_time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $review;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $restaurantName;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): self
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function getReviewTime(): ?\DateTimeInterface
    {
        return $this->review_time;
    }

    public function setReviewTime(\DateTimeInterface $review_time): self
    {
        $this->review_time = $review_time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getReview(): ?int
    {
        return $this->review;
    }

    public function setReview(int $review): self
    {
        $this->review = $review;

        return $this;
    }

    public function getRestaurantName(): ?string
    {
        return $this->restaurantName;
    }

    public function setRestaurantName(string $restaurantName): self
    {
        $this->restaurantName = $restaurantName;

        return $this;
    }
}

src/Service/Security/Authentication/Validation/Components/Form/FormValidatorInterface.php
<?php

namespace App\Service\Security\Authentication\Validation\Components\Form;

interface FormValidatorInterface
{
    public function validateForm(array $arrayOfFormData): array;
}

src/Service/Security/Authentication/Validation/Components/Form/Products/FormValidator.php
<?php

namespace App\Service\Security\Authentication\Validation\Components\Form\Products;

use App\Service\ClientSideGuru\Post\Authentication\SignUp\SignUpFormFetcherInterface;
use App\Service\Security\Authentication\Validation\Components\Form\FormValidatorInterface;
use App\Service\Security\Authentication\Validation\Objects\User\SignUpUser;
use App\Service\Security\Authentication\Validation\Supplier\ValidationSupplierInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class FormValidator implements FormValidatorInterface
{
    private $user;
    private $signUpFormFetcher;
    private $validator;
    private $validationSupplier;

    public function __construct(SignUpFormFetcherInterface $signUpFormFetcher, ValidatorInterface $validator, ValidationSupplierInterface $validationSupplier, LoggerInterface $logger)
    {
        $this->user = new SignUpUser();
        $this->signUpFormFetcher = $signUpFormFetcher;
        $this->validator = $validator;
        $this->validationSupplier = $validationSupplier;

        // dev
        $this->logger = $logger;
    }

    public function validateForm(array $arrayOfFormData): array
    {
        $username = $this->signUpFormFetcher->getUsername($arrayOfFormData);
        $this->user->setUsername($username);

        $password = $this->signUpFormFetcher->getPassword($arrayOfFormData);
        $this->user->setPassword($password);

        $firstName = $this->signUpFormFetcher->getFirstName($arrayOfFormData);
        $this->user->setFirstName($firstName);

        $lastName = $this->signUpFormFetcher->getLastName($arrayOfFormData);
        $this->user->setLastName($lastName);

        $errors = $this->validator->validate($this->user);


        if (count($errors) === 0) {
            return [];
        }

        return $this->validationSupplier->convertErrorsToArray($errors);
    }
}

templates/dashboard/activity/components/bookmarks.html.twig
<div>
    <h3><i class="far fa-bookmark"></i> Bookmarks <em><span class="text-muted">{{ amountOfBookmarks }}</span></em> <a class="btn btn-info float-right" href="#bookmarks">See More</a></h3>
    <hr>

    {% if bookmarks|length == 0 %}
        <h4 class="text-center">No Bookmarks Yet</h4>
    {% else %}

            <div class="row">

            {% for bookmark in bookmarks %}
                <div class="col-3 m-2 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src={{ "/photo/restaurant/cover-photo/" ~ bookmark.bookmark.restaurant.coverPhoto }} alt="">
                        <div class="card-body">

                            <a href={{ "/restaurants/" ~ bookmark.bookmark.restaurant.name ~ "/" ~ bookmark.bookmark.restaurant.id }}>
                                <h5 class="card-title"> {{ bookmark.bookmark.restaurant.name }} </h5>
                            </a>

                            <span><i class="fas fa-map-marker-alt"></i> {{ bookmark.bookmark.restaurant.location }} <i class="fas fa-star"></i> {{ bookmark.restaurant.rating}}</span>
                        </div>

                        <div class="card-footer">
                            <i class="far fa-clock"></i> Bookmarked at {{ bookmark.bookmark.bookmarkDateTime.format("Y-m-d H:i") }}
                        </div>
                    </div>
                </div>
            {% endfor %}

            </div>

    {% endif %}
</div>

templates/dashboard/activity/components/ratings.html.twig
<div>
    <h3><i class="fas fa-star"></i> Rated Restaurants <em><span class="text-muted">{{ amountOfRatings }}</span></em> <a href="#ratings" class="btn btn-info float-right">See More</a></h3>
    <hr>

    {% if reviews|length == 0 %}
        <h4 class="text-center">No Ratings Done Yet</h4>
    {% else %}
        {% for review in reviews %}
            <div class="row">
                <div class="col-6 mb-3">

                        <div class="card" style="width: 18rem">
                            <img src={{ "photo/restaurant/cover-photo/" ~ review.review.restaurant.coverPhoto }} class="card-img-top" alt="restaurant-img">
                            <div class="card-body">
                                <a href={{ "/restaurants/" ~ review.review.restaurant.name ~ "/" ~ review.review.restaurant.id }}>
                                    <h5 class="card-title"> {{ review.review.restaurant.name }} </h5>
                                </a>

                                <span><i class="fas fa-map-marker-alt"></i> {{ review.review.restaurant.location }} <i class="fas fa-star"></i> {{ review.restaurantRating }}</span>
                            </div>
                        </div>

                </div>

                {% set userRating = review.review.review %}
                {% set notRated = 5 - userRating %}
                <div class="col-6 align-middle">
                    <div>

                        {% for index in range(1, userRating) %}
                            {% include "base-components/rating/rated.html.twig" %}
                        {% endfor %}

                        {% if notRated != 0 %}
                            {% for index in range(1,notRated) %}
                                {% include "base-components/rating/not-rated.html.twig" %}
                            {% endfor %}
                        {% endif %}

                        <small class="text-muted"> rated at {{ review.review.date.format("Y-m-d") }} {{ review.review.reviewTime.format("H:i") }}</small>
                    </div>

                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>

templates/dashboard/activity/components/reservations.html.twig
<div>
    {# 1 #}
    <h3><i class="fas fa-book"></i> Reservations made <em><span class="text-muted">{{ amountOfReservations }}</span></em> <a href="#see-more" class="btn btn-info float-right">See More</a></h3>
    <hr>

    {% if reservations %}
        <h4>Upcoming Reservations</h4>

        <div class="row">
            {% for reservation in reservations %}
                <div class="card col-3 mr-4">
                    <h5 class="card-header text-center"><span>{{ reservation.restauran.name }}</span></h5>
                    <div class="card-body">
                        <div><i class="fas fa-map-marker-alt"></i> Location: {{ reservation.restauran.location }}</div>
                        <div><i class="fas fa-hashtag"></i> Table Number: {{ reservation.table.personAmount }}</div>
                        <div><i class="fas fa-hourglass-start"></i> Amount of Time: {{ reservation.amountOfTime }}</div>
                    </div>
                    <div class="card-footer">
                        <div><i class="fas fa-calendar"></i> Reservation time and date {{ reservation.reservationDate.format("Y-m-d") }} {{ reservation.reservationTime.format("H:i") }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>

    {% else %}
        <h4 class="text-center">No Upcoming Reservations</h4>
    {% endif %}
</div>