src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Restaurant", inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $restaurant;

    /**
     * @ORM\Column(type="time")
     */
    private $review_time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $review;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $restaurantName;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): self
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function getReviewTime(): ?\DateTimeInterface
    {
        return $this->review_time;
    }

    public function setReviewTime(\DateTimeInterface $review_time): self
    {
        $this->review_time = $review_time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getReview(): ?int
    {
        return $this->review;
    }

    public function setReview(int $review): self
    {
        $this->review = $review;

        return $this;
    }

    public function getRestaurantName(): ?string
    {
        return $this->restaurantName;
    }

    public function setRestaurantName(string $restaurantName): self
    {
        $this->restaurantName = $restaurantName;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $registration_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cookie_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Restaurant", mappedBy="user", orphanRemoval=true)
     */
    private $restaurant;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="user", orphanRemoval=true)
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="user", orphanRemoval=true)
     */
    private $reviews;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Bookmark", mappedBy="user", orphanRemoval=true)
     */
    private $bookmarks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="user", orphanRemoval=true)
     */
    private $notifications;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->bookmarks = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getRegistrationTime(): ?int
    {
        return $this->registration_time;
    }

    public function setRegistrationTime(int $registration_time): self
    {
        $this->registration_time = $registration_time;

        return $this;
    }

    public function getCookieId(): ?string
    {
        return $this->cookie_id;
    }

    public function setCookieId(string $cookie_id): self
    {
        $this->cookie_id = $cookie_id;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setRelation($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getRelation() === $this) {
                $reservation->setRelation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Restaurant[]
     */
    public function getRestaurant(): Collection
    {
        return $this->restaurant;
    }

    public function addRestaurant(Restaurant $restaurant): self
    {
        if (!$this->restaurant->contains($restaurant)) {
            $this->restaurant[] = $restaurant;
            $restaurant->setUser($this);
        }

        return $this;
    }

    public function removeRestaurant(Restaurant $restaurant): self
    {
        if ($this->restaurant->contains($restaurant)) {
            $this->restaurant->removeElement($restaurant);
            // set the owning side to null (unless already changed)
            if ($restaurant->getUser() === $this) {
                $restaurant->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getUser() === $this) {
                $review->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Bookmark[]
     */
    public function getBookmarks(): Collection
    {
        return $this->bookmarks;
    }

    public function addBookmark(Bookmark $bookmark): self
    {
        if (!$this->bookmarks->contains($bookmark)) {
            $this->bookmarks[] = $bookmark;
            $bookmark->setUser($this);
        }

        return $this;
    }

    public function removeBookmark(Bookmark $bookmark): self
    {
        if ($this->bookmarks->contains($bookmark)) {
            $this->bookmarks->removeElement($bookmark);
            // set the owning side to null (unless already changed)
            if ($bookmark->getUser() === $this) {
                $bookmark->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setUser($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getUser() === $this) {
                $notification->setUser(null);
            }
        }

        return $this;
    }
}

templates/restaurant/sections/review/comments.html.twig
{% if restaurant.comments|length == 0 %}
{% else %}

    <h4>Comments {{ restaurant.comments|length }}</h4>
    <hr>

    {% for comment in restaurant.comments|reverse %}
        <div class="mt-4">
            <div class="row">

                <div class="col-3">
                    <div>
                        <img src="/photo/user/default-imgs/user.png" alt={{ comment.user.firstName }}>
                    </div>

                    <div class="text-muted">
                        {{ comment.user.firstName }} {{ comment.user.lastName }}
                    </div>
                </div>

                <div class="col-9">
                    <div class="text-muted">
                        {{ comment.comment }}
                    </div>

                    <div class="text-muted text-right">
                        <small>at {{ comment.commentTime | date("d/m/y") }}</small>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    {% endfor %}

{% endif %}

{% block stylesheets %}
    <link rel="stylesheet" href="/css/restaurant/comment-section.css">
{% endblock %}

templates/restaurant/sections/review/interaction.html.twig
<div>
    <h4 class="text-center">Your Review</h4>
    <hr>
    <div>

        {% if  rating %}
            <div class="row mb-4">
                <div class="col-4">
                    <h5><span class="text-muted">Your Rating is </span><strong class="text-weight-bold">{{ rating.review }}</strong></h5>
                </div>
                <div class="col-8">
                    {% set notRated = 5 - rating.review %}

                    {% for index in range(1, rating.review) %}
                        {% include "base-components/rating/rated.html.twig" %}
                    {% endfor %}

                    {% if notRated != 0 %}
                        {% for index in range(1,notRated) %}
                            {% include "base-components/rating/not-rated.html.twig" %}
                        {% endfor %}
                    {% endif %}

                    <small class="text-muted"> rated at {{ rating.date.format("Y-m-d") }} {{ rating.reviewTime.format("H:i") }}</small>

                </div>
            </div>

        {% else %}
            <div>
                {% include "restaurant/sections/review/ratings.html.twig" %}
            </div>
        {% endif %}


        <div class="alert alert-success text-center" id="commentSubmitted">
            Your comment is <strong>submitted</strong>! To see it refresh this page.

            <div>
                <small class = text-muted>I was very lazy at that day and don't add js rendering :)</small>
            </div>
        </div>

        <div class="alert alert-warning text-center" id="submitError">
            Sth went wrong. Please try again!
        </div>

        <div class="input-group">

            <input id="comment" type="text" class="form-control" name="comment" ng-model="comment">

            <div class="input-group-append">
                <button class="btn btn-success" ng-click={{ "addComment('/restaurants/" ~ restaurant.id ~ "/comment')" }}>Add Comment</button>
            </div>
        </div>
    </div>
</div>

templates/restaurant/sections/review/ratings.html.twig
<div id="success">

</div>

<section id="rating-section" class="mt-4 mb-4">
    <div class="row">
        <div class="col-4">
            <h5 class="text-muted">Rate Please</h5>
        </div>

        <div id="rating" class="col-8">
            <div title="Very bad - 1" ng-click={{ "rate(1,'/restaurants/" ~ restaurant.id ~ "/rating')" }}>
                <i class="fas fa-star"></i>
            </div>
            <div title="Bad - 2" ng-click={{ "rate(2,'/restaurants/" ~ restaurant.id ~ "/rating')" }}>
                <i class="fas fa-star"></i>
            </div>
            <div title="Not Bad - 3" ng-click={{ "rate(3,'/restaurants/" ~ restaurant.id ~ "/rating')" }}>
                <i class="fas fa-star"></i>
            </div>
            <div title="Good - 4" ng-click={{ "rate(4,'/restaurants/" ~ restaurant.id ~ "/rating')" }}>
                <i class="fas fa-star"></i>
            </div>
            <div title="Grate - 5" ng-click={{ "rate(5,'/restaurants/" ~ restaurant.id ~ "/rating')" }}>
                <i class="fas fa-star"></i>
            </div>
        </div>
    </div>

{% block stylesheets %}
    <link rel="stylesheet" href="/css/restaurant/rating-section.css">
{% endblock %}